name: HPE Smart Storage Administrator
version: '1'
slug: hpessa
description: >-
  HPE Smart Storage Administrator (HPE SSA) offers a single interface that
  quickly sets up, configures and manages the HPE Smart Array controllers and
  the HPE SAS Host Bus Adapters (HBAs).
arch:
  - amd64
startup: application
boot: auto
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
webui: '[PROTO:ssl]://[HOST]:[PORT:80]/index.htm'
ingress: true
ingress_port: 0
init: false
panel_icon: 'mdi:database-edit'
map: []
full_access: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
hassio_api: true
auth_api: true
hassio_role: default
homeassistant_api: false
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  lang: list(en|ja|de|es|fr|it|pt|ru|zh)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
