---
name: Baikal
slug: baikal
version: 0.10.1
description: Baikal is a Cal and CardDAV server, based on sabre/dav, that includes an administrative interface for easy management.
url: https://github.com/d-two/hassio-addons
startup: services
init: false
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
arch:
- aarch64
- amd64
- armhf
boot: auto
map:
- config:rw
- ssl:ro
ports:
  80/tcp: 8013
ports_description:
  80/tcp: Web UI port
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: match(^[^/].*)
  keyfile: match(^[^/].*)
