---
name: Ps3NetServer
slug: ps3netserver
version: 0.1.2-NAS
description: This is a Docker container for ps3netsrv (or ps3netsvr).
url: https://github.com/d-two/hassio-addons/tree/main/ps3netsrv
startup: application
init: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
boot: auto
ports:
  38008/tcp: 38008
ports_description:
  38008/tcp: Network port
privileged:
- SYS_ADMIN
- DAC_READ_SEARCH
schema:
  cifsdomain: str?
  cifspassword: str
  cifsusername: str
  networkdisks: str
